import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt-BR' | 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Auth
    'auth.title': 'Controle de Estoque',
    'auth.subtitle': 'Entre com suas credenciais para acessar o sistema',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.login': 'Entrar',
    'auth.logging_in': 'Entrando...',
    'auth.fill_all_fields': 'Por favor, preencha todos os campos.',
    'auth.invalid_credentials': 'Email ou senha incorretos.',
    'auth.error': 'Erro ao fazer login. Tente novamente.',
    'auth.success': 'Login realizado com sucesso!',
    'auth.welcome': 'Bem-vindo ao sistema de estoque.',
    'auth.test_users': 'Usuários de teste:',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Gestão de Estoque',
    'nav.stock_entry': 'Preenchimento',
    'nav.shopping_list': 'Lista de Compras',
    'nav.audit_history': 'Histórico de Auditoria',
    'nav.users': 'Usuários',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Bem-vindo ao sistema de controle de estoque',
    'dashboard.total_items': 'Total de Itens',
    'dashboard.low_stock': 'Estoque Baixo',
    'dashboard.expired_items': 'Itens Vencidos',
    'dashboard.expiring_soon': 'Próximo ao Vencimento',
    'dashboard.up_to_date': 'Em Dia',
    'dashboard.quick_info': 'Informações Rápidas',
    'dashboard.your_profile': 'Seu perfil',
    'dashboard.color_legend': 'Legenda de cores',
    'dashboard.expiring_legend': 'Item próximo ao vencimento (até 3 dias)',
    'dashboard.expired_legend': 'Item com validade vencida',
    'dashboard.low_stock_legend': 'Estoque abaixo do mínimo',
    'dashboard.click_to_view': 'Clique para ver detalhes',

    // Inventory
    'inventory.title': 'Gestão de Estoque',
    'inventory.subtitle': 'Cadastre e organize categorias e itens do estoque',
    'inventory.new_category': 'Nova Categoria',
    'inventory.edit_category': 'Editar Categoria',
    'inventory.category_name': 'Nome da categoria',
    'inventory.category_placeholder': 'Ex: Proteínas, Laticínios...',
    'inventory.create_category': 'Criar Categoria',
    'inventory.save_changes': 'Salvar Alterações',
    'inventory.no_categories': 'Nenhuma categoria',
    'inventory.start_creating': 'Comece criando sua primeira categoria de produtos.',
    'inventory.no_items_category': 'Nenhum item nesta categoria',
    'inventory.add_first_item': 'Adicionar primeiro item',
    'inventory.new_item': 'Novo Item',
    'inventory.edit_item': 'Editar Item',
    'inventory.product_name': 'Nome do produto',
    'inventory.product_placeholder': 'Ex: Carne de sol, Frango...',
    'inventory.category': 'Categoria',
    'inventory.select_category': 'Selecione uma categoria',
    'inventory.unit': 'Unidade',
    'inventory.min_stock': 'Estoque mínimo',
    'inventory.create_item': 'Criar Item',
    'inventory.confirm_delete_category': 'Tem certeza? Isso irá excluir todos os itens desta categoria.',
    'inventory.confirm_delete_item': 'Tem certeza que deseja excluir este item?',
    'inventory.items': 'itens',
    'inventory.item': 'item',

    // Stock Entry
    'stock_entry.title': 'Preenchimento de Estoque',
    'stock_entry.subtitle': 'Atualize rapidamente as quantidades e validades',
    'stock_entry.discard': 'Descartar',
    'stock_entry.save_changes': 'Salvar Alterações',
    'stock_entry.all_categories': 'Todas as categorias',
    'stock_entry.search_product': 'Buscar produto...',
    'stock_entry.expiring_legend': 'Próximo ao vencimento',
    'stock_entry.low_stock_legend': 'Estoque abaixo do mínimo',
    'stock_entry.no_items': 'Nenhum item encontrado',
    'stock_entry.register_first': 'Cadastre itens na tela de Gestão de Estoque primeiro.',
    'stock_entry.adjust_filters': 'Tente ajustar os filtros de busca.',
    'stock_entry.no_changes': 'Nenhuma alteração para salvar',
    'stock_entry.saved': 'Alterações salvas!',
    'stock_entry.items_updated': 'itens atualizados',
    'stock_entry.item_updated': 'item atualizado',
    'stock_entry.below_min': 'abaixo do mínimo',
    'stock_entry.near_expiry': 'próximo do vencimento',
    'stock_entry.discard_confirm': 'Descartar todas as alterações?',
    'stock_entry.select_date': 'Selecionar',
    'stock_entry.filter_low_stock': 'Filtrando: Estoque Baixo',
    'stock_entry.filter_expiring': 'Filtrando: Próximo ao Vencimento',
    'stock_entry.clear_filter': 'Limpar filtro',
    'stock_entry.staff_restriction_notice': 'Como funcionário, você só pode aumentar o estoque. Para reduzir, use o botão "Baixa de Estoque".',
    'stock_entry.staff_no_decrease': 'Funcionários não podem diminuir o estoque diretamente. Use a função "Baixa de Estoque".',
    'stock_entry.entry_reason': 'Entrada de estoque',
    'stock_entry.adjustment_reason': 'Ajuste manual',

    'users.title': 'Usuários',
    'users.subtitle': 'Gerencie os usuários da sua operação',
    'users.new_user': 'Novo Usuário',
    'users.add_user': 'Adicionar Novo Usuário',
    'users.edit_user': 'Editar Usuário',
    'users.full_name': 'Nome completo',
    'users.user_type': 'Tipo de usuário',
    'users.staff_desc': 'Staff - Pode preencher estoque',
    'users.admin_desc': 'Admin - Gerencia funcionários',
    'users.host_desc': 'Host - Acesso total ao sistema',
    'users.create_user': 'Criar Usuário',
    'users.creating': 'Criando...',
    'users.no_users': 'Nenhum usuário',
    'users.add_users_desc': 'Adicione usuários para gerenciar o estoque.',
    'users.registered_at': 'Cadastrado em',
    'users.you': '(você)',
    'users.fill_all_fields': 'Preencha todos os campos',
    'users.password_min': 'A senha deve ter pelo menos 6 caracteres',
    'users.created_success': 'Usuário criado com sucesso!',
    'users.updated_success': 'Usuário atualizado com sucesso!',
    'users.email_exists': 'Este email já está cadastrado',
    'users.create_error': 'Erro ao criar usuário',
    'users.update_error': 'Erro ao atualizar usuário',
    'users.permission_denied': 'Você não tem permissão para esta ação',
    'users.delete_self_error': 'Você não pode excluir seu próprio usuário',
    'users.confirm_delete': 'Tem certeza que deseja excluir este usuário?',
    'users.deleted': 'Usuário removido!',
    'users.delete_error': 'Erro ao excluir usuário',
    'users.load_error': 'Erro ao carregar usuários',
    'users.new_password': 'Nova senha',
    'users.password_leave_empty': 'Deixe em branco para manter a senha atual',

    // Settings
    'settings.title': 'Configurações',
    'settings.subtitle': 'Personalize sua experiência no sistema',
    'settings.general': 'Geral',
    'settings.suppliers_tab': 'Fornecedores',
    'settings.language': 'Idioma',
    'settings.language_desc': 'Selecione o idioma do sistema',
    'settings.theme': 'Tema',
    'settings.theme_desc': 'Escolha entre modo claro ou escuro',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.currency': 'Moeda',
    'settings.currency_desc': 'Selecione a moeda do sistema',
    'settings.session': 'Sessão',
    'settings.session_desc': 'Gerencie sua sessão atual',
    'settings.logout': 'Sair da Conta',
    'settings.logout_desc': 'Encerrar a sessão e voltar à tela de login',
    'settings.logout_confirm': 'Deseja realmente encerrar a sessão?',
    'settings.logout_confirm_title': 'Encerrar Sessão',

    // Table headers
    'table.product': 'Produto',
    'table.unit': 'Unidade',
    'table.min_stock': 'Est. Mínimo',
    'table.current_qty': 'Qtd Atual',
    'table.count_date': 'Data Contagem',
    'table.expiry': 'Validade',
    'table.responsible': 'Responsável',
    'table.category': 'Categoria',
    'table.name': 'Nome',
    'table.type': 'Tipo',

    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.admin': 'Admin',
    'common.staff': 'Staff',
    'common.host': 'Host',
    'common.saving': 'Salvando...',

    // Withdrawal
    'withdrawal.title': 'Baixa de Estoque',
    'withdrawal.description': 'Registre a saída de produtos do estoque',
    'withdrawal.product': 'Produto',
    'withdrawal.select_product': 'Selecione um produto...',
    'withdrawal.search_product': 'Buscar produto...',
    'withdrawal.no_products': 'Nenhum produto encontrado',
    'withdrawal.quantity': 'Quantidade',
    'withdrawal.available': 'Disponível',
    'withdrawal.reason_label': 'Motivo',
    'withdrawal.reason.sale': 'Venda',
    'withdrawal.reason.waste': 'Desperdício',
    'withdrawal.reason.internal_use': 'Uso Interno',
    'withdrawal.reason.expired': 'Vencido',
    'withdrawal.reason.other': 'Outro',
    'withdrawal.notes': 'Observações',
    'withdrawal.notes_placeholder': 'Informações adicionais (opcional)',
    'withdrawal.responsible': 'Responsável',
    'withdrawal.confirm': 'Confirmar Baixa',
    'withdrawal.processing': 'Processando...',
    'withdrawal.success': 'Baixa realizada!',
    'withdrawal.success_low_stock': '⚠️ Atenção: Estoque baixo!',
    'withdrawal.error': 'Erro ao processar a baixa. Tente novamente.',
    'withdrawal.insufficient_stock': 'Quantidade maior que o estoque disponível',
    'withdrawal.invalid_quantity': 'Informe uma quantidade válida',
    'withdrawal.not_authenticated': 'Você precisa estar autenticado',
    'withdrawal.low_stock_warning': 'Atenção: O estoque ficará abaixo do mínimo!',
    'withdrawal.remaining_after': 'Restará',
    'withdrawal.button': 'Baixa de Estoque',

    // Audit History
    'audit.title': 'Histórico de Auditoria',
    'audit.subtitle': 'Visualize todas as movimentações de estoque',
    'audit.search_placeholder': 'Buscar por produto, usuário ou motivo...',
    'audit.all_movements': 'Todos os movimentos',
    'audit.type_withdrawal': 'Baixa',
    'audit.type_entry': 'Entrada',
    'audit.type_adjustment': 'Ajuste',
    'audit.no_records': 'Nenhum registro',
    'audit.no_records_desc': 'Ainda não há movimentações de estoque registradas.',
    'audit.records_label': 'registros',
    'audit.col_datetime': 'Data/Hora',
    'audit.col_user': 'Usuário',
    'audit.col_product': 'Produto',
    'audit.col_type': 'Tipo',
    'audit.col_quantity': 'Qtd Movimentada',
    'audit.col_balance': 'Saldo Final',
    'audit.col_reason': 'Motivo',
    'audit.unknown_product': 'Produto desconhecido',
    'audit.unknown_user': 'Usuário desconhecido',

    // Shopping List
    'shopping.title': 'Lista de Compras Inteligente',
    'shopping.subtitle': 'Produtos que precisam de atenção',
    'shopping.tag_expired': 'Vencido',
    'shopping.tag_expiring_soon': 'Vencimento Próximo',
    'shopping.tag_below_min': 'Abaixo do Mínimo',
    'shopping.expired_desc': 'Produtos com data de validade vencida',
    'shopping.expiring_soon_desc': 'Produtos com validade em até 3 dias',
    'shopping.below_min_desc': 'Produtos abaixo do estoque mínimo',
    'shopping.items_needing_attention': 'Itens que precisam de atenção',
    'shopping.all_good': 'Tudo em ordem!',
    'shopping.no_items_desc': 'Nenhum produto precisa de reposição no momento.',
    'shopping.current': 'Atual',
    'shopping.minimum': 'Mínimo',
    'shopping.suggestion': 'Sugestão',
    'shopping.reason': 'Motivo',
    'shopping.copy': 'Copiar Texto',
    'shopping.whatsapp': 'Enviar via WhatsApp',
    'shopping.print': 'Imprimir',
    'shopping.copied': 'Copiado!',
    'shopping.copied_desc': 'Lista copiada para a área de transferência.',
    'shopping.copy_error': 'Erro ao copiar a lista.',
    'shopping.current_qty': 'Qtd Atual',
    'shopping.quantity': 'Quantidade',
    'shopping.no_items_pending': 'Nenhum item pendente para compra',
    'shopping.no_supplier': 'Sem Fornecedor',
    'shopping.supplier': 'Fornecedor',
    'shopping.send_order': 'Enviar Pedido',

    // Suppliers
    'suppliers.title': 'Fornecedores',
    'suppliers.description': 'Cadastre fornecedores para organizar seus pedidos',
    'suppliers.new': 'Novo Fornecedor',
    'suppliers.edit': 'Editar Fornecedor',
    'suppliers.name': 'Nome',
    'suppliers.name_placeholder': 'Ex: Distribuidora XYZ',
    'suppliers.whatsapp': 'WhatsApp',
    'suppliers.whatsapp_hint': 'Inclua o código do país e DDD',
    'suppliers.form_description': 'Preencha os dados do fornecedor',
    'suppliers.create': 'Criar Fornecedor',
    'suppliers.no_suppliers': 'Nenhum fornecedor cadastrado',
    'suppliers.add_first': 'Adicionar primeiro fornecedor',
    'suppliers.created': 'Fornecedor criado com sucesso!',
    'suppliers.updated': 'Fornecedor atualizado!',
    'suppliers.deleted': 'Fornecedor removido!',
    'suppliers.confirm_delete': 'Tem certeza que deseja excluir este fornecedor?',
    'suppliers.load_error': 'Erro ao carregar fornecedores',
    'suppliers.save_error': 'Erro ao salvar fornecedor',
    'suppliers.delete_error': 'Erro ao excluir fornecedor',
    'suppliers.fill_all_fields': 'Preencha todos os campos',

    // Dishes / Menu
    'nav.dishes': 'Cardápio',
    'dishes.title': 'Cardápio',
    'dishes.subtitle': 'Gerencie os pratos e suas fichas técnicas',
    'dishes.new': 'Novo Prato',
    'dishes.edit': 'Editar Prato',
    'dishes.name': 'Nome do prato',
    'dishes.name_placeholder': 'Ex: Cachopo, Picanha...',
    'dishes.description': 'Descrição',
    'dishes.description_placeholder': 'Descrição opcional do prato',
    'dishes.form_description': 'Defina os ingredientes e quantidades consumidas por venda',
    'dishes.ingredients': 'Ingredientes',
    'dishes.add_ingredient': 'Adicionar',
    'dishes.no_ingredients': 'Adicione ingredientes do estoque',
    'dishes.select_ingredient': 'Selecione um ingrediente',
    'dishes.quantity': 'Qtd',
    'dishes.create': 'Criar Prato',
    'dishes.created': 'Prato criado com sucesso!',
    'dishes.updated': 'Prato atualizado!',
    'dishes.deleted': 'Prato excluído!',
    'dishes.confirm_delete': 'Tem certeza que deseja excluir este prato?',
    'dishes.load_error': 'Erro ao carregar pratos',
    'dishes.save_error': 'Erro ao salvar prato',
    'dishes.delete_error': 'Erro ao excluir prato',
    'dishes.name_required': 'Informe o nome do prato',
    'dishes.ingredients_required': 'Adicione pelo menos um ingrediente',
    'dishes.no_dishes': 'Nenhum prato cadastrado',
    'dishes.no_dishes_desc': 'Comece cadastrando os pratos do seu cardápio',
    'dishes.launch_sale': 'Lançar Venda',
    'dishes.sale_title': 'Simular Venda',
    'dishes.sale_quantity': 'Quantidade de pratos',
    'dishes.insufficient_stock': 'Estoque insuficiente',
    'dishes.stock_issue_item': '{name}: necessário {needed} {unit}, disponível {available} {unit}',
    'dishes.ingredients_to_deduct': 'Ingredientes a descontar',
    'dishes.confirm_sale': 'Confirmar Venda',
    'dishes.confirm_sale_title': 'Confirmar venda?',
    'dishes.confirm_sale_desc': 'Esta ação irá descontar os ingredientes do estoque para {quantity}x {dish}.',
    'dishes.confirm': 'Confirmar',
    'dishes.sale_success': 'Venda registrada!',
    'dishes.sale_error': 'Erro ao processar venda',
    'dishes.sale_reason': 'Venda de prato',
    'dishes.price': 'Preço',
    'dishes.price_placeholder': 'Ex: 25.90',

    // Dining Room / PDV
    'nav.dining_room': 'Salão',
    'dining.title': 'Salão',
    'dining.subtitle': 'Gerencie as mesas e pedidos do restaurante',
    'dining.load_error': 'Erro ao carregar dados do salão',
    'dining.status_free': 'Livre',
    'dining.status_occupied': 'Ocupada',
    'dining.status_reserved': 'Reservada',
    'dining.status_updated': 'Status atualizado!',
    'dining.table': 'Mesa',
    'dining.tables': 'Mesas',
    'dining.table_options_desc': 'Configure o status e ocupação da mesa',
    'dining.status': 'Status',
    'dining.guest_count': 'Quantidade de pessoas',
    'dining.view_order': 'Ver Pedido',
    'dining.new_counter_order': 'Novo Pedido Balcão',
    'dining.counter_orders': 'Pedidos de Balcão',
    'dining.counter_order_desc': 'Crie um pedido para retirada no balcão',
    'dining.customer_name': 'Nome do Cliente',
    'dining.customer_name_placeholder': 'Ex: João ou Pedido #123',
    'dining.start_order': 'Iniciar Pedido',
    'dining.order_description': 'Gerencie o pedido desta mesa',
    'dining.waiter': 'Garçom',
    'dining.guests': 'Pessoas',
    'dining.thanks': 'Obrigado pela preferência!',
    'dining.no_items': 'Nenhum item no pedido',
    'dining.add_item': 'Adicionar',
    'dining.print_bill': 'Imprimir',
    'dining.close_order': 'Fechar Conta',
    'dining.menu': 'Cardápio',
    'dining.select_dish': 'Selecione um prato para adicionar ao pedido',
    'dining.no_dishes': 'Nenhum prato cadastrado no cardápio',
    'dining.item_added': 'Item adicionado!',
    'dining.item_removed': 'Item removido',
    'dining.add_item_error': 'Erro ao adicionar item',
    'dining.order_create_error': 'Erro ao criar pedido',
    'dining.order_closed': 'Conta fechada!',
    'dining.close_error': 'Erro ao fechar conta',
    'dining.close_order_confirm': 'Fechar conta?',
    'dining.close_order_desc': 'Esta ação encerrará o pedido e liberará a mesa.',
    'dining.confirm_close': 'Fechar',
    'dining.receipt': 'Cupom',
    'dining.print': 'Imprimir Cupom',
    'dining.stock_insufficient': 'Estoque Insuficiente',
    'dining.needed': 'necessário',
    'dining.available': 'disponível',
    'dining.sale_reason': 'Pedido mesa',
  },
  'es': {
    // Auth
    'auth.title': 'Control de Inventario',
    'auth.subtitle': 'Ingrese sus credenciales para acceder al sistema',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.login': 'Iniciar sesión',
    'auth.logging_in': 'Iniciando...',
    'auth.fill_all_fields': 'Por favor, complete todos los campos.',
    'auth.invalid_credentials': 'Correo o contraseña incorrectos.',
    'auth.error': 'Error al iniciar sesión. Inténtelo de nuevo.',
    'auth.success': '¡Inicio de sesión exitoso!',
    'auth.welcome': 'Bienvenido al sistema de inventario.',
    'auth.test_users': 'Usuarios de prueba:',

    // Sidebar
    'nav.dashboard': 'Panel',
    'nav.inventory': 'Gestión de Inventario',
    'nav.stock_entry': 'Registro',
    'nav.shopping_list': 'Lista de Compras',
    'nav.audit_history': 'Historial de Auditoría',
    'nav.users': 'Usuarios',
    'nav.settings': 'Configuración',
    'nav.logout': 'Salir',

    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.subtitle': 'Bienvenido al sistema de control de inventario',
    'dashboard.total_items': 'Total de Artículos',
    'dashboard.low_stock': 'Stock Bajo',
    'dashboard.expired_items': 'Artículos Vencidos',
    'dashboard.expiring_soon': 'Próximo a Vencer',
    'dashboard.up_to_date': 'Al Día',
    'dashboard.quick_info': 'Información Rápida',
    'dashboard.your_profile': 'Tu perfil',
    'dashboard.color_legend': 'Leyenda de colores',
    'dashboard.expiring_legend': 'Artículo próximo a vencer (hasta 3 días)',
    'dashboard.expired_legend': 'Artículo con fecha de vencimiento pasada',
    'dashboard.low_stock_legend': 'Stock por debajo del mínimo',
    'dashboard.click_to_view': 'Clic para ver detalles',

    // Inventory
    'inventory.title': 'Gestión de Inventario',
    'inventory.subtitle': 'Registre y organice categorías y artículos del inventario',
    'inventory.new_category': 'Nueva Categoría',
    'inventory.edit_category': 'Editar Categoría',
    'inventory.category_name': 'Nombre de la categoría',
    'inventory.category_placeholder': 'Ej: Proteínas, Lácteos...',
    'inventory.create_category': 'Crear Categoría',
    'inventory.save_changes': 'Guardar Cambios',
    'inventory.no_categories': 'Sin categorías',
    'inventory.start_creating': 'Comience creando su primera categoría de productos.',
    'inventory.no_items_category': 'Sin artículos en esta categoría',
    'inventory.add_first_item': 'Agregar primer artículo',
    'inventory.new_item': 'Nuevo Artículo',
    'inventory.edit_item': 'Editar Artículo',
    'inventory.product_name': 'Nombre del producto',
    'inventory.product_placeholder': 'Ej: Carne seca, Pollo...',
    'inventory.category': 'Categoría',
    'inventory.select_category': 'Seleccione una categoría',
    'inventory.unit': 'Unidad',
    'inventory.min_stock': 'Stock mínimo',
    'inventory.create_item': 'Crear Artículo',
    'inventory.confirm_delete_category': '¿Está seguro? Esto eliminará todos los artículos de esta categoría.',
    'inventory.confirm_delete_item': '¿Está seguro de que desea eliminar este artículo?',
    'inventory.items': 'artículos',
    'inventory.item': 'artículo',

    // Stock Entry
    'stock_entry.title': 'Registro de Inventario',
    'stock_entry.subtitle': 'Actualice rápidamente cantidades y fechas de vencimiento',
    'stock_entry.discard': 'Descartar',
    'stock_entry.save_changes': 'Guardar Cambios',
    'stock_entry.all_categories': 'Todas las categorías',
    'stock_entry.search_product': 'Buscar producto...',
    'stock_entry.expiring_legend': 'Próximo a vencer',
    'stock_entry.low_stock_legend': 'Stock por debajo del mínimo',
    'stock_entry.no_items': 'No se encontraron artículos',
    'stock_entry.register_first': 'Registre artículos en la pantalla de Gestión de Inventario primero.',
    'stock_entry.adjust_filters': 'Intente ajustar los filtros de búsqueda.',
    'stock_entry.no_changes': 'Sin cambios para guardar',
    'stock_entry.saved': '¡Cambios guardados!',
    'stock_entry.items_updated': 'artículos actualizados',
    'stock_entry.item_updated': 'artículo actualizado',
    'stock_entry.below_min': 'por debajo del mínimo',
    'stock_entry.near_expiry': 'próximo al vencimiento',
    'stock_entry.discard_confirm': '¿Descartar todos los cambios?',
    'stock_entry.select_date': 'Seleccionar',
    'stock_entry.filter_low_stock': 'Filtrando: Stock Bajo',
    'stock_entry.filter_expiring': 'Filtrando: Próximo a Vencer',
    'stock_entry.clear_filter': 'Limpiar filtro',
    'stock_entry.staff_restriction_notice': 'Como empleado, solo puede aumentar el stock. Para reducir, use el botón "Salida de Stock".',
    'stock_entry.staff_no_decrease': 'Los empleados no pueden disminuir el stock directamente. Use la función "Salida de Stock".',
    'stock_entry.entry_reason': 'Entrada de inventario',
    'stock_entry.adjustment_reason': 'Ajuste manual',

    'users.title': 'Usuarios',
    'users.subtitle': 'Gestione los usuarios de su operación',
    'users.new_user': 'Nuevo Usuario',
    'users.add_user': 'Agregar Nuevo Usuario',
    'users.edit_user': 'Editar Usuario',
    'users.full_name': 'Nombre completo',
    'users.user_type': 'Tipo de usuario',
    'users.staff_desc': 'Staff - Puede registrar inventario',
    'users.admin_desc': 'Admin - Gestiona empleados',
    'users.host_desc': 'Host - Acceso total al sistema',
    'users.create_user': 'Crear Usuario',
    'users.creating': 'Creando...',
    'users.no_users': 'Sin usuarios',
    'users.add_users_desc': 'Agregue usuarios para gestionar el inventario.',
    'users.registered_at': 'Registrado el',
    'users.you': '(tú)',
    'users.fill_all_fields': 'Complete todos los campos',
    'users.password_min': 'La contraseña debe tener al menos 6 caracteres',
    'users.created_success': '¡Usuario creado exitosamente!',
    'users.updated_success': '¡Usuario actualizado exitosamente!',
    'users.email_exists': 'Este correo ya está registrado',
    'users.create_error': 'Error al crear usuario',
    'users.update_error': 'Error al actualizar usuario',
    'users.permission_denied': 'No tiene permiso para esta acción',
    'users.delete_self_error': 'No puede eliminar su propio usuario',
    'users.confirm_delete': '¿Está seguro de que desea eliminar este usuario?',
    'users.deleted': '¡Usuario eliminado!',
    'users.delete_error': 'Error al eliminar usuario',
    'users.load_error': 'Error al cargar usuarios',
    'users.new_password': 'Nueva contraseña',
    'users.password_leave_empty': 'Deje en blanco para mantener la contraseña actual',

    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Personalice su experiencia en el sistema',
    'settings.general': 'General',
    'settings.suppliers_tab': 'Proveedores',
    'settings.language': 'Idioma',
    'settings.language_desc': 'Seleccione el idioma del sistema',
    'settings.theme': 'Tema',
    'settings.theme_desc': 'Elija entre modo claro u oscuro',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.currency': 'Moneda',
    'settings.currency_desc': 'Seleccione la moneda del sistema',
    'settings.session': 'Sesión',
    'settings.session_desc': 'Gestione su sesión actual',
    'settings.logout': 'Cerrar Sesión',
    'settings.logout_desc': 'Finalizar la sesión y volver al inicio de sesión',
    'settings.logout_confirm': '¿Realmente desea cerrar la sesión?',
    'settings.logout_confirm_title': 'Cerrar Sesión',

    // Table headers
    'table.product': 'Producto',
    'table.unit': 'Unidad',
    'table.min_stock': 'Stock Mín.',
    'table.current_qty': 'Cant. Actual',
    'table.count_date': 'Fecha Conteo',
    'table.expiry': 'Vencimiento',
    'table.responsible': 'Responsable',
    'table.category': 'Categoría',
    'table.name': 'Nombre',
    'table.type': 'Tipo',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.admin': 'Admin',
    'common.staff': 'Staff',
    'common.host': 'Host',
    'common.saving': 'Guardando...',

    // Withdrawal
    'withdrawal.title': 'Baja de Stock',
    'withdrawal.description': 'Registre la salida de productos del inventario',
    'withdrawal.product': 'Producto',
    'withdrawal.select_product': 'Seleccione un producto...',
    'withdrawal.search_product': 'Buscar producto...',
    'withdrawal.no_products': 'No se encontraron productos',
    'withdrawal.quantity': 'Cantidad',
    'withdrawal.available': 'Disponible',
    'withdrawal.reason_label': 'Motivo',
    'withdrawal.reason.sale': 'Venta',
    'withdrawal.reason.waste': 'Desperdicio',
    'withdrawal.reason.internal_use': 'Uso Interno',
    'withdrawal.reason.expired': 'Vencido',
    'withdrawal.reason.other': 'Otro',
    'withdrawal.notes': 'Observaciones',
    'withdrawal.notes_placeholder': 'Información adicional (opcional)',
    'withdrawal.responsible': 'Responsable',
    'withdrawal.confirm': 'Confirmar Baja',
    'withdrawal.processing': 'Procesando...',
    'withdrawal.success': '¡Baja realizada!',
    'withdrawal.success_low_stock': '⚠️ Atención: ¡Stock bajo!',
    'withdrawal.error': 'Error al procesar la baja. Inténtelo de nuevo.',
    'withdrawal.insufficient_stock': 'Cantidad mayor que el stock disponible',
    'withdrawal.invalid_quantity': 'Ingrese una cantidad válida',
    'withdrawal.not_authenticated': 'Debe estar autenticado',
    'withdrawal.low_stock_warning': '¡Atención: El stock quedará por debajo del mínimo!',
    'withdrawal.remaining_after': 'Quedará',
    'withdrawal.button': 'Baja de Stock',

    // Audit History
    'audit.title': 'Historial de Auditoría',
    'audit.subtitle': 'Visualice todos los movimientos de inventario',
    'audit.search_placeholder': 'Buscar por producto, usuario o motivo...',
    'audit.all_movements': 'Todos los movimientos',
    'audit.type_withdrawal': 'Baja',
    'audit.type_entry': 'Entrada',
    'audit.type_adjustment': 'Ajuste',
    'audit.no_records': 'Sin registros',
    'audit.no_records_desc': 'Aún no hay movimientos de inventario registrados.',
    'audit.records_label': 'registros',
    'audit.col_datetime': 'Fecha/Hora',
    'audit.col_user': 'Usuario',
    'audit.col_product': 'Producto',
    'audit.col_type': 'Tipo',
    'audit.col_quantity': 'Cant. Movida',
    'audit.col_balance': 'Saldo Final',
    'audit.col_reason': 'Motivo',
    'audit.unknown_product': 'Producto desconocido',
    'audit.unknown_user': 'Usuario desconocido',

    // Shopping List
    'shopping.title': 'Lista de Compras Inteligente',
    'shopping.subtitle': 'Productos que necesitan atención',
    'shopping.tag_expired': 'Vencido',
    'shopping.tag_expiring_soon': 'Próximo a Vencer',
    'shopping.tag_below_min': 'Bajo Mínimo',
    'shopping.expired_desc': 'Productos con fecha de vencimiento pasada',
    'shopping.expiring_soon_desc': 'Productos con vencimiento en hasta 3 días',
    'shopping.below_min_desc': 'Productos por debajo del stock mínimo',
    'shopping.items_needing_attention': 'Artículos que necesitan atención',
    'shopping.all_good': '¡Todo en orden!',
    'shopping.no_items_desc': 'Ningún producto necesita reposición en este momento.',
    'shopping.current': 'Actual',
    'shopping.minimum': 'Mínimo',
    'shopping.suggestion': 'Sugerencia',
    'shopping.reason': 'Motivo',
    'shopping.copy': 'Copiar Texto',
    'shopping.whatsapp': 'Enviar por WhatsApp',
    'shopping.print': 'Imprimir',
    'shopping.copied': '¡Copiado!',
    'shopping.copied_desc': 'Lista copiada al portapapeles.',
    'shopping.copy_error': 'Error al copiar la lista.',
    'shopping.current_qty': 'Cant. Actual',
    'shopping.quantity': 'Cantidad',
    'shopping.no_items_pending': 'Ningún artículo pendiente de compra',
    'shopping.no_supplier': 'Sin Proveedor',
    'shopping.supplier': 'Proveedor',
    'shopping.send_order': 'Enviar Pedido',

    // Suppliers
    'suppliers.title': 'Proveedores',
    'suppliers.description': 'Registre proveedores para organizar sus pedidos',
    'suppliers.new': 'Nuevo Proveedor',
    'suppliers.edit': 'Editar Proveedor',
    'suppliers.name': 'Nombre',
    'suppliers.name_placeholder': 'Ej: Distribuidora XYZ',
    'suppliers.whatsapp': 'WhatsApp',
    'suppliers.whatsapp_hint': 'Incluya el código del país y código de área',
    'suppliers.form_description': 'Complete los datos del proveedor',
    'suppliers.create': 'Crear Proveedor',
    'suppliers.no_suppliers': 'Ningún proveedor registrado',
    'suppliers.add_first': 'Agregar primer proveedor',
    'suppliers.created': '¡Proveedor creado exitosamente!',
    'suppliers.updated': '¡Proveedor actualizado!',
    'suppliers.deleted': '¡Proveedor eliminado!',
    'suppliers.confirm_delete': '¿Está seguro de que desea eliminar este proveedor?',
    'suppliers.load_error': 'Error al cargar proveedores',
    'suppliers.save_error': 'Error al guardar proveedor',
    'suppliers.delete_error': 'Error al eliminar proveedor',
    'suppliers.fill_all_fields': 'Complete todos los campos',

    // Dishes / Menu
    'nav.dishes': 'Menú',
    'dishes.title': 'Menú',
    'dishes.subtitle': 'Administre los platos y sus fichas técnicas',
    'dishes.new': 'Nuevo Plato',
    'dishes.edit': 'Editar Plato',
    'dishes.name': 'Nombre del plato',
    'dishes.name_placeholder': 'Ej: Cachopo, Picanha...',
    'dishes.description': 'Descripción',
    'dishes.description_placeholder': 'Descripción opcional del plato',
    'dishes.form_description': 'Defina los ingredientes y cantidades consumidas por venta',
    'dishes.ingredients': 'Ingredientes',
    'dishes.add_ingredient': 'Agregar',
    'dishes.no_ingredients': 'Agregue ingredientes del inventario',
    'dishes.select_ingredient': 'Seleccione un ingrediente',
    'dishes.quantity': 'Cant.',
    'dishes.create': 'Crear Plato',
    'dishes.created': '¡Plato creado con éxito!',
    'dishes.updated': '¡Plato actualizado!',
    'dishes.deleted': '¡Plato eliminado!',
    'dishes.confirm_delete': '¿Está seguro de que desea eliminar este plato?',
    'dishes.load_error': 'Error al cargar platos',
    'dishes.save_error': 'Error al guardar plato',
    'dishes.delete_error': 'Error al eliminar plato',
    'dishes.name_required': 'Ingrese el nombre del plato',
    'dishes.ingredients_required': 'Agregue al menos un ingrediente',
    'dishes.no_dishes': 'Ningún plato registrado',
    'dishes.no_dishes_desc': 'Comience registrando los platos de su menú',
    'dishes.launch_sale': 'Registrar Venta',
    'dishes.sale_title': 'Simular Venta',
    'dishes.sale_quantity': 'Cantidad de platos',
    'dishes.insufficient_stock': 'Stock insuficiente',
    'dishes.stock_issue_item': '{name}: necesario {needed} {unit}, disponible {available} {unit}',
    'dishes.ingredients_to_deduct': 'Ingredientes a descontar',
    'dishes.confirm_sale': 'Confirmar Venta',
    'dishes.confirm_sale_title': '¿Confirmar venta?',
    'dishes.confirm_sale_desc': 'Esta acción descontará los ingredientes del inventario para {quantity}x {dish}.',
    'dishes.confirm': 'Confirmar',
    'dishes.sale_success': '¡Venta registrada!',
    'dishes.sale_error': 'Error al procesar venta',
    'dishes.sale_reason': 'Venta de plato',
    'dishes.price': 'Precio',
    'dishes.price_placeholder': 'Ej: 25.90',

    // Dining Room / PDV
    'nav.dining_room': 'Salón',
    'dining.title': 'Salón',
    'dining.subtitle': 'Gestione las mesas y pedidos del restaurante',
    'dining.load_error': 'Error al cargar datos del salón',
    'dining.status_free': 'Libre',
    'dining.status_occupied': 'Ocupada',
    'dining.status_reserved': 'Reservada',
    'dining.status_updated': '¡Estado actualizado!',
    'dining.table': 'Mesa',
    'dining.tables': 'Mesas',
    'dining.table_options_desc': 'Configure el estado y ocupación de la mesa',
    'dining.status': 'Estado',
    'dining.guest_count': 'Cantidad de personas',
    'dining.view_order': 'Ver Pedido',
    'dining.new_counter_order': 'Nuevo Pedido Mostrador',
    'dining.counter_orders': 'Pedidos de Mostrador',
    'dining.counter_order_desc': 'Cree un pedido para retiro en mostrador',
    'dining.customer_name': 'Nombre del Cliente',
    'dining.customer_name_placeholder': 'Ej: Juan o Pedido #123',
    'dining.start_order': 'Iniciar Pedido',
    'dining.order_description': 'Gestione el pedido de esta mesa',
    'dining.waiter': 'Camarero',
    'dining.guests': 'Personas',
    'dining.thanks': '¡Gracias por su preferencia!',
    'dining.no_items': 'Ningún ítem en el pedido',
    'dining.add_item': 'Agregar',
    'dining.print_bill': 'Imprimir',
    'dining.close_order': 'Cerrar Cuenta',
    'dining.menu': 'Menú',
    'dining.select_dish': 'Seleccione un plato para agregar al pedido',
    'dining.no_dishes': 'Ningún plato registrado en el menú',
    'dining.item_added': '¡Ítem agregado!',
    'dining.item_removed': 'Ítem eliminado',
    'dining.add_item_error': 'Error al agregar ítem',
    'dining.order_create_error': 'Error al crear pedido',
    'dining.order_closed': '¡Cuenta cerrada!',
    'dining.close_error': 'Error al cerrar cuenta',
    'dining.close_order_confirm': '¿Cerrar cuenta?',
    'dining.close_order_desc': 'Esta acción finalizará el pedido y liberará la mesa.',
    'dining.confirm_close': 'Cerrar',
    'dining.receipt': 'Recibo',
    'dining.print': 'Imprimir Recibo',
    'dining.stock_insufficient': 'Stock Insuficiente',
    'dining.needed': 'necesario',
    'dining.available': 'disponible',
    'dining.sale_reason': 'Pedido mesa',
  },
  'en': {
    // Auth
    'auth.title': 'Inventory Control',
    'auth.subtitle': 'Enter your credentials to access the system',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Sign In',
    'auth.logging_in': 'Signing in...',
    'auth.fill_all_fields': 'Please fill in all fields.',
    'auth.invalid_credentials': 'Invalid email or password.',
    'auth.error': 'Login failed. Please try again.',
    'auth.success': 'Login successful!',
    'auth.welcome': 'Welcome to the inventory system.',
    'auth.test_users': 'Test users:',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory Management',
    'nav.stock_entry': 'Stock Entry',
    'nav.shopping_list': 'Shopping List',
    'nav.audit_history': 'Audit History',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Welcome to the inventory control system',
    'dashboard.total_items': 'Total Items',
    'dashboard.low_stock': 'Low Stock',
    'dashboard.expired_items': 'Expired Items',
    'dashboard.expiring_soon': 'Expiring Soon',
    'dashboard.up_to_date': 'Up to Date',
    'dashboard.quick_info': 'Quick Info',
    'dashboard.your_profile': 'Your profile',
    'dashboard.color_legend': 'Color legend',
    'dashboard.expiring_legend': 'Item expiring soon (up to 3 days)',
    'dashboard.expired_legend': 'Item past expiration date',
    'dashboard.low_stock_legend': 'Stock below minimum',
    'dashboard.click_to_view': 'Click to view details',

    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.subtitle': 'Register and organize categories and inventory items',
    'inventory.new_category': 'New Category',
    'inventory.edit_category': 'Edit Category',
    'inventory.category_name': 'Category name',
    'inventory.category_placeholder': 'Ex: Proteins, Dairy...',
    'inventory.create_category': 'Create Category',
    'inventory.save_changes': 'Save Changes',
    'inventory.no_categories': 'No categories',
    'inventory.start_creating': 'Start by creating your first product category.',
    'inventory.no_items_category': 'No items in this category',
    'inventory.add_first_item': 'Add first item',
    'inventory.new_item': 'New Item',
    'inventory.edit_item': 'Edit Item',
    'inventory.product_name': 'Product name',
    'inventory.product_placeholder': 'Ex: Dried meat, Chicken...',
    'inventory.category': 'Category',
    'inventory.select_category': 'Select a category',
    'inventory.unit': 'Unit',
    'inventory.min_stock': 'Minimum stock',
    'inventory.create_item': 'Create Item',
    'inventory.confirm_delete_category': 'Are you sure? This will delete all items in this category.',
    'inventory.confirm_delete_item': 'Are you sure you want to delete this item?',
    'inventory.items': 'items',
    'inventory.item': 'item',

    // Stock Entry
    'stock_entry.title': 'Stock Entry',
    'stock_entry.subtitle': 'Quickly update quantities and expiry dates',
    'stock_entry.discard': 'Discard',
    'stock_entry.save_changes': 'Save Changes',
    'stock_entry.all_categories': 'All categories',
    'stock_entry.search_product': 'Search product...',
    'stock_entry.expiring_legend': 'Expiring soon',
    'stock_entry.low_stock_legend': 'Stock below minimum',
    'stock_entry.no_items': 'No items found',
    'stock_entry.register_first': 'Register items in Inventory Management first.',
    'stock_entry.adjust_filters': 'Try adjusting the search filters.',
    'stock_entry.no_changes': 'No changes to save',
    'stock_entry.saved': 'Changes saved!',
    'stock_entry.items_updated': 'items updated',
    'stock_entry.item_updated': 'item updated',
    'stock_entry.below_min': 'below minimum',
    'stock_entry.near_expiry': 'near expiry',
    'stock_entry.discard_confirm': 'Discard all changes?',
    'stock_entry.select_date': 'Select',
    'stock_entry.filter_low_stock': 'Filtering: Low Stock',
    'stock_entry.filter_expiring': 'Filtering: Expiring Soon',
    'stock_entry.clear_filter': 'Clear filter',
    'stock_entry.staff_restriction_notice': 'As a staff member, you can only increase stock. To reduce, use the "Stock Withdrawal" button.',
    'stock_entry.staff_no_decrease': 'Staff members cannot decrease stock directly. Use the "Stock Withdrawal" function.',
    'stock_entry.entry_reason': 'Stock entry',
    'stock_entry.adjustment_reason': 'Manual adjustment',

    'users.title': 'Users',
    'users.subtitle': 'Manage your operation users',
    'users.new_user': 'New User',
    'users.add_user': 'Add New User',
    'users.edit_user': 'Edit User',
    'users.full_name': 'Full name',
    'users.user_type': 'User type',
    'users.staff_desc': 'Staff - Can enter stock',
    'users.admin_desc': 'Admin - Manages employees',
    'users.host_desc': 'Host - Full system access',
    'users.create_user': 'Create User',
    'users.creating': 'Creating...',
    'users.no_users': 'No users',
    'users.add_users_desc': 'Add users to manage inventory.',
    'users.registered_at': 'Registered on',
    'users.you': '(you)',
    'users.fill_all_fields': 'Fill in all fields',
    'users.password_min': 'Password must be at least 6 characters',
    'users.created_success': 'User created successfully!',
    'users.updated_success': 'User updated successfully!',
    'users.email_exists': 'This email is already registered',
    'users.create_error': 'Error creating user',
    'users.update_error': 'Error updating user',
    'users.permission_denied': 'You do not have permission for this action',
    'users.delete_self_error': 'You cannot delete your own user',
    'users.confirm_delete': 'Are you sure you want to delete this user?',
    'users.deleted': 'User removed!',
    'users.delete_error': 'Error deleting user',
    'users.load_error': 'Error loading users',
    'users.new_password': 'New password',
    'users.password_leave_empty': 'Leave empty to keep current password',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your system experience',
    'settings.general': 'General',
    'settings.suppliers_tab': 'Suppliers',
    'settings.language': 'Language',
    'settings.language_desc': 'Select the system language',
    'settings.theme': 'Theme',
    'settings.theme_desc': 'Choose between light or dark mode',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.currency': 'Currency',
    'settings.currency_desc': 'Select the system currency',
    'settings.session': 'Session',
    'settings.session_desc': 'Manage your current session',
    'settings.logout': 'Sign Out',
    'settings.logout_desc': 'End the session and return to login',
    'settings.logout_confirm': 'Are you sure you want to sign out?',
    'settings.logout_confirm_title': 'Sign Out',

    // Table headers
    'table.product': 'Product',
    'table.unit': 'Unit',
    'table.min_stock': 'Min. Stock',
    'table.current_qty': 'Current Qty',
    'table.count_date': 'Count Date',
    'table.expiry': 'Expiry',
    'table.responsible': 'Responsible',
    'table.category': 'Category',
    'table.name': 'Name',
    'table.type': 'Type',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.admin': 'Admin',
    'common.staff': 'Staff',
    'common.host': 'Host',
    'common.saving': 'Saving...',

    // Withdrawal
    'withdrawal.title': 'Stock Withdrawal',
    'withdrawal.description': 'Record the removal of products from inventory',
    'withdrawal.product': 'Product',
    'withdrawal.select_product': 'Select a product...',
    'withdrawal.search_product': 'Search product...',
    'withdrawal.no_products': 'No products found',
    'withdrawal.quantity': 'Quantity',
    'withdrawal.available': 'Available',
    'withdrawal.reason_label': 'Reason',
    'withdrawal.reason.sale': 'Sale',
    'withdrawal.reason.waste': 'Waste',
    'withdrawal.reason.internal_use': 'Internal Use',
    'withdrawal.reason.expired': 'Expired',
    'withdrawal.reason.other': 'Other',
    'withdrawal.notes': 'Notes',
    'withdrawal.notes_placeholder': 'Additional information (optional)',
    'withdrawal.responsible': 'Responsible',
    'withdrawal.confirm': 'Confirm Withdrawal',
    'withdrawal.processing': 'Processing...',
    'withdrawal.success': 'Withdrawal completed!',
    'withdrawal.success_low_stock': '⚠️ Warning: Low stock!',
    'withdrawal.error': 'Error processing withdrawal. Try again.',
    'withdrawal.insufficient_stock': 'Quantity exceeds available stock',
    'withdrawal.invalid_quantity': 'Enter a valid quantity',
    'withdrawal.not_authenticated': 'You must be authenticated',
    'withdrawal.low_stock_warning': 'Warning: Stock will be below minimum!',
    'withdrawal.remaining_after': 'Remaining',
    'withdrawal.button': 'Stock Withdrawal',

    // Audit History
    'audit.title': 'Audit History',
    'audit.subtitle': 'View all stock movements',
    'audit.search_placeholder': 'Search by product, user or reason...',
    'audit.all_movements': 'All movements',
    'audit.type_withdrawal': 'Withdrawal',
    'audit.type_entry': 'Entry',
    'audit.type_adjustment': 'Adjustment',
    'audit.no_records': 'No records',
    'audit.no_records_desc': 'No stock movements recorded yet.',
    'audit.records_label': 'records',
    'audit.col_datetime': 'Date/Time',
    'audit.col_user': 'User',
    'audit.col_product': 'Product',
    'audit.col_type': 'Type',
    'audit.col_quantity': 'Qty Moved',
    'audit.col_balance': 'Final Balance',
    'audit.col_reason': 'Reason',
    'audit.unknown_product': 'Unknown product',
    'audit.unknown_user': 'Unknown user',

    // Shopping List
    'shopping.title': 'Smart Shopping List',
    'shopping.subtitle': 'Products that need attention',
    'shopping.tag_expired': 'Expired',
    'shopping.tag_expiring_soon': 'Expiring Soon',
    'shopping.tag_below_min': 'Below Minimum',
    'shopping.expired_desc': 'Products past their expiration date',
    'shopping.expiring_soon_desc': 'Products expiring within 3 days',
    'shopping.below_min_desc': 'Products below minimum stock',
    'shopping.items_needing_attention': 'Items needing attention',
    'shopping.all_good': 'All good!',
    'shopping.no_items_desc': 'No products need restocking at the moment.',
    'shopping.current': 'Current',
    'shopping.minimum': 'Minimum',
    'shopping.suggestion': 'Suggestion',
    'shopping.reason': 'Reason',
    'shopping.copy': 'Copy Text',
    'shopping.whatsapp': 'Send via WhatsApp',
    'shopping.print': 'Print',
    'shopping.copied': 'Copied!',
    'shopping.copied_desc': 'List copied to clipboard.',
    'shopping.copy_error': 'Error copying the list.',
    'shopping.current_qty': 'Current Qty',
    'shopping.quantity': 'Quantity',
    'shopping.no_items_pending': 'No items pending for purchase',
    'shopping.no_supplier': 'No Supplier',
    'shopping.supplier': 'Supplier',
    'shopping.send_order': 'Send Order',

    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.description': 'Register suppliers to organize your orders',
    'suppliers.new': 'New Supplier',
    'suppliers.edit': 'Edit Supplier',
    'suppliers.name': 'Name',
    'suppliers.name_placeholder': 'Ex: XYZ Distributor',
    'suppliers.whatsapp': 'WhatsApp',
    'suppliers.whatsapp_hint': 'Include country and area code',
    'suppliers.form_description': 'Fill in supplier details',
    'suppliers.create': 'Create Supplier',
    'suppliers.no_suppliers': 'No suppliers registered',
    'suppliers.add_first': 'Add first supplier',
    'suppliers.created': 'Supplier created successfully!',
    'suppliers.updated': 'Supplier updated!',
    'suppliers.deleted': 'Supplier removed!',
    'suppliers.confirm_delete': 'Are you sure you want to delete this supplier?',
    'suppliers.load_error': 'Error loading suppliers',
    'suppliers.save_error': 'Error saving supplier',
    'suppliers.delete_error': 'Error deleting supplier',
    'suppliers.fill_all_fields': 'Fill in all fields',

    // Dishes / Menu
    'nav.dishes': 'Menu',
    'dishes.title': 'Menu',
    'dishes.subtitle': 'Manage dishes and their technical sheets',
    'dishes.new': 'New Dish',
    'dishes.edit': 'Edit Dish',
    'dishes.name': 'Dish name',
    'dishes.name_placeholder': 'Ex: Cachopo, Picanha...',
    'dishes.description': 'Description',
    'dishes.description_placeholder': 'Optional dish description',
    'dishes.form_description': 'Define ingredients and quantities consumed per sale',
    'dishes.ingredients': 'Ingredients',
    'dishes.add_ingredient': 'Add',
    'dishes.no_ingredients': 'Add ingredients from inventory',
    'dishes.select_ingredient': 'Select an ingredient',
    'dishes.quantity': 'Qty',
    'dishes.create': 'Create Dish',
    'dishes.created': 'Dish created successfully!',
    'dishes.updated': 'Dish updated!',
    'dishes.deleted': 'Dish deleted!',
    'dishes.confirm_delete': 'Are you sure you want to delete this dish?',
    'dishes.load_error': 'Error loading dishes',
    'dishes.save_error': 'Error saving dish',
    'dishes.delete_error': 'Error deleting dish',
    'dishes.name_required': 'Enter the dish name',
    'dishes.ingredients_required': 'Add at least one ingredient',
    'dishes.no_dishes': 'No dishes registered',
    'dishes.no_dishes_desc': 'Start by registering your menu dishes',
    'dishes.launch_sale': 'Launch Sale',
    'dishes.sale_title': 'Simulate Sale',
    'dishes.sale_quantity': 'Number of dishes',
    'dishes.insufficient_stock': 'Insufficient stock',
    'dishes.stock_issue_item': '{name}: needed {needed} {unit}, available {available} {unit}',
    'dishes.ingredients_to_deduct': 'Ingredients to deduct',
    'dishes.confirm_sale': 'Confirm Sale',
    'dishes.confirm_sale_title': 'Confirm sale?',
    'dishes.confirm_sale_desc': 'This action will deduct ingredients from stock for {quantity}x {dish}.',
    'dishes.confirm': 'Confirm',
    'dishes.sale_success': 'Sale recorded!',
    'dishes.sale_error': 'Error processing sale',
    'dishes.sale_reason': 'Dish sale',
    'dishes.price': 'Price',
    'dishes.price_placeholder': 'Ex: 25.90',

    // Dining Room / PDV
    'nav.dining_room': 'Dining Room',
    'dining.title': 'Dining Room',
    'dining.subtitle': 'Manage tables and orders',
    'dining.load_error': 'Error loading dining room data',
    'dining.status_free': 'Free',
    'dining.status_occupied': 'Occupied',
    'dining.status_reserved': 'Reserved',
    'dining.status_updated': 'Status updated!',
    'dining.table': 'Table',
    'dining.tables': 'Tables',
    'dining.table_options_desc': 'Configure table status and occupancy',
    'dining.status': 'Status',
    'dining.guest_count': 'Number of guests',
    'dining.view_order': 'View Order',
    'dining.new_counter_order': 'New Counter Order',
    'dining.counter_orders': 'Counter Orders',
    'dining.counter_order_desc': 'Create an order for counter pickup',
    'dining.customer_name': 'Customer Name',
    'dining.customer_name_placeholder': 'E.g.: John or Order #123',
    'dining.start_order': 'Start Order',
    'dining.order_description': 'Manage this table order',
    'dining.waiter': 'Waiter',
    'dining.guests': 'Guests',
    'dining.thanks': 'Thank you for your preference!',
    'dining.no_items': 'No items in order',
    'dining.add_item': 'Add',
    'dining.print_bill': 'Print',
    'dining.close_order': 'Close Order',
    'dining.menu': 'Menu',
    'dining.select_dish': 'Select a dish to add to the order',
    'dining.no_dishes': 'No dishes registered in menu',
    'dining.item_added': 'Item added!',
    'dining.item_removed': 'Item removed',
    'dining.add_item_error': 'Error adding item',
    'dining.order_create_error': 'Error creating order',
    'dining.order_closed': 'Order closed!',
    'dining.close_error': 'Error closing order',
    'dining.close_order_confirm': 'Close order?',
    'dining.close_order_desc': 'This action will finalize the order and free the table.',
    'dining.confirm_close': 'Close',
    'dining.receipt': 'Receipt',
    'dining.print': 'Print Receipt',
    'dining.stock_insufficient': 'Insufficient Stock',
    'dining.needed': 'needed',
    'dining.available': 'available',
    'dining.sale_reason': 'Table order',
  },
};

const LANGUAGE_KEY = 'app_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANGUAGE_KEY);
    if (saved && ['pt-BR', 'es', 'en'].includes(saved)) {
      return saved as Language;
    }
    return 'pt-BR'; // Default - will show language selector on first load
  });

  const [showSelector, setShowSelector] = useState(() => {
    return !localStorage.getItem(LANGUAGE_KEY);
  });

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    setShowSelector(false);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function useShowLanguageSelector() {
  return !localStorage.getItem(LANGUAGE_KEY);
}
